### ISSUE TITLE
Manifest V3????

### ISSUE THREAD

**Issue by D1998Avid** [Konnor88/anti-grabify#18]
Hello,

I was wondering if this extension will be upgraded to manifestv3 since its only a matter of time before manifest 2 extensions are delisted. Is a manifest v3 version in the works? This extension is very helpful for me and I would love to see a manifest v3 update in the future

**Comment by Konnor88** [comment]
Hi, I was able to complete the manifest v3 version a few weeks ago and will be submitting to Chrome and Edge stores soon. However, since Firefox has not announced a date on manifest v2 being discontinued on their browser, Anti-Grabify for Firefox will remain on Manifest V2. I will be updating the repository soon.

**Comment by Konnor88** [comment]
Ok, Google has approved the manifest v3 version in their web store.
